---
- name: Deleting K8s VM on proxmox
  hosts: prox02
  become: false
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    proxmox_node: prox02
    virtual_machines:
    - name: CTRL-01
      vm_id: 111
      vm_ip_address: 192.168.101.11
      start: false
      delete: true
    - name: CTRL-02
      vm_id: 112
      vm_ip_address: 192.168.101.12
      start: false
      delete: true
    - name: CTRL-03
      vm_id: 113
      vm_ip_address: 192.168.101.13
      start: false
      delete: true
    - name: WRK-01
      vm_id: 121
      vm_ip_address: 192.168.101.21
      start: false
      delete: true
    - name: WRK-02
      vm_id: 122
      vm_ip_address: 192.168.101.22
      start: false
      delete: true
    - name: WRK-03
      vm_id: 123
      vm_ip_address: 192.168.101.23
      start: false
      delete: true
  roles:
    - roles/delete-vm
