#SPDX-License-Identifier: MIT-0
---
# tasks file for k8s

- name: Set module br_netfiter
  modprobe:
    name: br_netfilter
    state: present
    persistent: present

- name: Set module overlay
  modprobe:
    name: overlay
    state: present
    persistent: present

- name: Set IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes

- name: Set IPv4 bridging
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present
    reload: yes
