---
- name: Download signing key 
  shell:
    cmd: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg"
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Setting up repository for docker
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu  {{ ansible_lsb.codename }} stable"
    filename: docker
    state: present
    update_cache: yes

- name: Installing necessary packages
  apt:
    pkg:
      - openjdk-21-jre
      - git
      - ansible
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-compose-plugin
    update_cache: 
    
- name: Adding user into docker group
  user:
    name: ansible
    groups: docker 
    append: true 

- name: Creating directory for agent start script 
  file:
    path: /usr/local/jenkins-service 
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Setting up agent script
  copy:
    src: start-agent.sh
    dest: /usr/local/jenkins-service
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Creating systemd file
  copy:
    src: jenkins-agent.service
    dest: /etc/systemd/system/
    mode: '0755'