#SPDX-License-Identifier: MIT-0
---
# tasks file for jenkins

- name: Setting up Controller
  include_tasks: '01-setup-controller.yml'
  when: "'jenkins_controllers' in group_names"

- name: Setting up Agents
  include_tasks: '02-setup-agent.yml'
  when: "'jenkins_agents' in group_names"
