#SPDX-License-Identifier: MIT-0
---
# tasks file for k8s-cluster

- name: Installing Keepalived and HAProxy
  apt:
    pkg:
      - keepalived 
      - haproxy 
    update_cache: yes

- name: Setting up keepalived config file 
  template:
    src: keepalived.conf.j2
    dest: /tmp/keepalived.conf

- name: Setting up haproxy config file 
  template:
    src: haproxy.cfg.j2 
    dest: /tmp/haproxy.cfg