#SPDX-License-Identifier: MIT-0
---
# tasks file for k8s-cluster

- name: Installing Keepalived and HAProxy
  apt:
    pkg:
      - keepalived 
      - haproxy 
    update_cache: yes

- name: Setting up keepalived config file 
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf

- name: Setting up health check script 
  copy:
    src: check_apiserver.sh
    dest: /etc/keepalived
    mode: '0755'

- name: Setting up haproxy config file 
  template:
    src: haproxy.cfg.j2 
    dest: /etc/haproxy/haproxy.cfg

- name: Starting and enable Keepalived
  systemd_service:
    name: keepalived
    state: started
    enabled: true

- name: Starting and enable HAProxy
  systemd_service:
    name: haproxy
    state: started
    enabled: true