records:
  - name: lab.mmkbmss.com
    nameserver: ns1
    forward_records:
      - name: ns1
        ip: 192.168.100.250
        type: A
      - name: ns2
        ip: 192.168.101.250
        type: A
      - name: jump01
        ip: 192.168.100.251
        type: A
      - name: jump02
        ip: 192.168.101.251
        type: A
      - name: strg01
        ip: 192.168.100.249
        type: A
      - name: strg02
        ip: 192.168.101.249
        type: A

