records:
  - name: lab.mmkbmss.com
    ptr: 168.192
    nameserver: ns2
    nameserver_ip: 192.168.101.248
    reverse_records:
      - name: ns1 
        ip: "250.100"
      - name: ns2
        ip: "250.101"
      - name: jump01
        ip: "251.100"
      - name: jump02
        ip: "251.101"

