records:
  - name: lab.mmkbmss.com
    nameserver: ns1
    forward_records:
      - name: ns1
        ip: 192.168.100.250
        type: A
      - name: ns2
        ip: 192.168.101.250
        type: A
      - name: jump01
        ip: 192.168.100.251
        type: A
      - name: jump02
        ip: 192.168.101.251
        type: A
      - name: docker01
        ip: 192.168.100.249
        type: A
      - name: strg02
        ip: 192.168.101.249
        type: A
      - name: prox01
        ip: 192.168.100.254
        type: A
      - name: prox02
        ip: 192.168.101.254
        type: A 
      - name: ctrl01
        ip: 192.168.101.11
        type: A
      - name: ctrl02
        ip: 192.168.101.12
        type: A
      - name: ctrl03
        ip: 192.168.101.254
        type: A
      - name: wrk01
        ip: 192.168.101.21
        type: A
      - name: wrk02
        ip: 192.168.101.22
        type: A
      - name: wrk03
        ip: 192.168.101.23
        type: A
