records:
  - name: lab.mmkbmss.com
    ptr: 168.192
    nameserver: ns1
    nameserver_ip: 192.168.100.250
    reverse_records:
      - name: ns1 
        ip: "250.100"
      - name: ns2 
        ip: "250.101"
      - name: jump01
        ip: "250.100"
      - name: jump02
        ip: "251.101"
      - name: docker01
        ip: "249.100"
      - name: strg02
        ip: "249.101"
      - name: prox01
        ip: "254.100"
      - name: prox02
        ip: "254.101"
