---
proxmox_node: prox02
proxmox_token_secret: "{{ lookup('env', 'PROX02_TOKEN_ID') }}"
gateway: 192.168.101.1
virtual_machines:
  - name: EVE-01
    vm_id: 103
    vm_ip_address: 192.168.101.253
    start: false
    delete: false
  - name: DNS02
    vm_id: 105
    vm_ip_address: 192.168.101.250
    start: false
    delete: false
