---
proxmox_node: prox02
virtual_machines:
  - name: JNKN-01
    vm_id: 102
    vm_ip_address: 192.168.101.250
    start: false
  - name: EVE-01
    vm_id: 103
    vm_ip_address: 192.168.101.253
    start: false
  - name: JNKN-AGNT-01
    vm_id: 104
    vm_ip_address: 192.168.101.249
    start: false
  - name: CTRL-01
    vm_id: 105
    vm_ip_address: 192.168.101.11
    start: false
  - name: CTRL-02
    vm_id: 106
    vm_ip_address: 192.168.101.12
    start: false
  - name: CTRL-03
    vm_id: 107
    vm_ip_address: 192.168.101.13
    start: false
  - name: WRK-01
    vm_id: 108
    vm_ip_address: 192.168.101.21
    start: false
  - name: WRK-02
    vm_id: 109
    vm_ip_address: 192.168.101.22
    start: false
  - name: JNKN-02
    vm_id: 110
    vm_ip_address: 192.168.101.248
    start: false