---
proxmox_node: prox02
proxmox_token_secret: "{{ lookup('env', 'PROX02_TOKEN_ID') }}"
gateway: 192.168.101.1
virtual_machines:
  - name: EVE-01
    vm_id: 103
    vm_ip_address: 192.168.101.253
    start: false
    delete: false
  - name: JUMP02
    vm_id: 104
    vm_ip_address: 192.168.101.251
    start: false
    delete: false
  - name: DNS02
    vm_id: 105
    vm_ip_address: 192.168.101.250
    start: false
    delete: false
  - name: STRG02
    vm_id: 106
    vm_ip_address: 192.168.101.249
    start: false
    delete: false
  - name: CTRL-01
    vm_id: 111
    vm_ip_address: 192.168.101.11
    start: false
    delete: false
  - name: CTRL-02
    vm_id: 112
    vm_ip_address: 192.168.101.12
    start: false
    delete: false
  - name: CTRL-03
    vm_id: 113
    vm_ip_address: 192.168.101.13
    start: false
    delete: false
  - name: WRK-01
    vm_id: 121
    vm_ip_address: 192.168.101.21
    start: false
    delete: false
  - name: WRK-02
    vm_id: 122
    vm_ip_address: 192.168.101.22
    start: false
    delete: false
  - name: WRK-03
    vm_id: 123
    vm_ip_address: 192.168.101.23
    start: false
    delete: false
