---
proxmox_node: prox01
proxmox_token_secret: "{{ lookup('env', 'PROX01_TOKEN_ID') }}"
gateway: 192.168.100.1
virtual_machines:
  - name: JUMP01
    vm_id: 104
    vm_ip_address: 192.168.100.251
    start: false
    delete: false
  - name: DNS01
    vm_id: 105
    vm_ip_address: 192.168.100.250
    start: false
    delete: false
  - name: DOCKER01
    vm_id: 106
    vm_ip_address: 192.168.100.249
    start: false
    delete: false
