---
proxmox_node: prox01
proxmox_token_secret: "{{ lookup('env', 'PROX01_TOKEN_ID') }}"
virtual_machines:
  - name: JUMP-01
    vm_id: 102
    vm_ip_address: 192.168.100.253
    start: false
    delete: false

